name: Deploy via FTP

on:
  push:
    branches:
      - main  # Ou o nome da sua branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ—ï¸ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: ğŸ“¦ Instalar dependÃªncias e Build
        run: |
          npm install
          npm run build

      - name: ğŸš€ Upload FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          # AJUSTE AQUI: O caminho da pasta no seu servidor para o subdomÃ­nio
          server-dir: ./mapamental.josevschmidt.com.br/